### ISSUE TITLE
Cannot Move Right

### ISSUE THREAD

**Issue by rkho** [m-arnold/m-arnold.github.io#1]
Pressing 'D' on the keyboard does not allow the player to move right, restricting the player's overall movements to up, down, and left :)

**Comment by adlaika** [comment]
Can you reproduce this issue? I'm not having the same problem.

**Comment by rkho** [comment]
Alright, I've isolated the issue. Looks like Vimium doesn't play nice with this, so I had to tell it to not listen for key presses on `d` on the page. Closing the issue :)
